### PR TITLE
Allow for cascade delete of BelongsTo and MorpthTo

### PR DESCRIPTION
**Pull request by pascaldls**
Sometimes you may want to cascade delete  BelongsTo or MorpthTo

### CODE REVIEW

**Comment by patrickcarlohickman** [comment]
Can you provide an example of when you may want to do this? BelongsTo was specifically not included, as it is typically the child in the relationship, and it doesn't make sense to delete a parent when deleting a child.

**Comment by pascaldls** [comment]
I think my specific case is quite unique to my code. 

I have a HealthDomaine, CarDomaine, ... and Domaine Class 

The Domaine class is morpthTo Health, Car, ... However the HealthDomaine and CarDomaine is never directly used as we want to access all domaines at all times and kept track of id by domaine this is easier for my client. 

So when deleting a domaine i want the morth class to be deleted. 

In very few cases like mine it makes perfect sense. I dont see the harm for others having this enable. may be a warning in the docs. 

Thanks for taking the time to review

**Comment by pascaldls** [comment]
> I think my specific case is quite unique to my code.
> 
> I have a HealthDomaine, CarDomaine, ... and Domaine Class
> 
> The Domaine class is morpthTo Health, Car, ... However the HealthDomaine and CarDomaine is never directly used as we want to access all domaines at all times and kept track of id by domaine this is easier for my client.
> 
> So when deleting a domaine i want the morth class to be deleted.
> 
> In very few cases like mine it makes perfect sense. I dont see the harm for others having this enable. may be a warning in the docs.
> 
> Thanks for taking the time to review

@patrickcarlohickman

**Comment by pascaldls** [comment]
> Can you provide an example of when you may want to do this? BelongsTo was specifically not included, as it is typically the child in the relationship, and it doesn't make sense to delete a parent when deleting a child.

**Comment by pascaldls** [comment]
> Can you provide an example of when you may want to do this? BelongsTo was specifically not included, as it is typically the child in the relationship, and it doesn't make sense to delete a parent when deleting a child.
@patrickcarlohickman 
I think my specific case is quite unique to my code.

I have a HealthDomaine, CarDomaine, ... and Domaine Class

The Domaine class is morpthTo Health, Car, ... However the HealthDomaine and CarDomaine is never directly used as we want to access all domaines at all times and kept track of id by domaine this is easier for my client.

So when deleting a domaine i want the morth class to be deleted.

In very few cases like mine it makes perfect sense. I dont see the harm for others having this enable. may be a warning in the docs.

Thanks for taking the time to review

**Comment by pascaldls** [comment]
@patrickcarlohickman Hi please revert back thanks

**Pull request closed without merging**
